Improved Storybooks and added tag link in navigation
rhinobase/raftyui pull request #15
Opened 2023-12-05 12:31 UTC by Gajendra-singh-r

- [x] Added tag link in `docs`
- [x] Improved stories of all components in `storybook`

2023-12-06 11:42 UTC, LuckySharma014 requested changes

2023-12-06 11:42 UTC, LuckySharma014 commented on apps/storybook/src/tab.stories.tsx
>    },
Add select for orientation

2023-12-06 11:42 UTC, LuckySharma014 commented on apps/storybook/src/tab.stories.tsx
> +        <Tab
- Remove 2nd tab and pass all args props to 1st tab
- Also remove line that says variant=enclosed

2023-12-06 11:42 UTC, LuckySharma014 commented on apps/storybook/src/table.stories.tsx
> +    variant: "simple",
Add isBarebone to args

2023-12-06 11:42 UTC, LuckySharma014 commented on apps/storybook/src/toggle-group.stories.tsx
> +      <ToggleGroup type="multiple">
Pass size prop from args to both functions' ToggleGroup components

2023-12-07 05:54 UTC, LuckySharma014 requested changes

2023-12-07 05:54 UTC, LuckySharma014 commented on apps/storybook/src/list.stories.tsx
> +export const Unordered_List: Story = {
Remove _(underscore) from function name

2023-12-07 05:54 UTC, LuckySharma014 commented on apps/storybook/src/list.stories.tsx
> +export const Ordered_List: Story = {
Remove _(underscore) from function name

2023-12-07 06:04 UTC, LuckySharma014 requested changes

2023-12-07 06:16 UTC, Gajendra-singh-r commented on apps/storybook/src/alertdialog.stories.tsx
>        <AlertDialogTrigger>Open</AlertDialogTrigger>
xl size  can not be passed in trigger

2023-12-07 08:26 UTC, LuckySharma014 approved these changes

2023-12-11 05:09 UTC, merged