Added Pagination to rafty
rhinobase/raftyui pull request #23
Opened 2023-12-08 07:17 UTC by Gajendra-singh-r

- [x] Created pagination component
- [x] Added `docs` for pagination 
- [x] Created `storybook` for pagination

2023-12-08 08:06 UTC, LuckySharma014 requested changes
Did a overview review for now but will do a brief review after they are done with requested changes

2023-12-08 08:06 UTC, LuckySharma014 commented on apps/docs/app/docs/components/pagination/page.md
> +## size
Write it in capitalized casing

2023-12-08 08:06 UTC, LuckySharma014 commented on apps/docs/app/docs/components/pagination/page.md
> +## showQuickJumper
Write it in capitalized casing

2023-12-08 08:06 UTC, LuckySharma014 commented on apps/docs/app/docs/components/pagination/page.md
> +## total_number
Write it in capitalized casing

2023-12-08 08:06 UTC, LuckySharma014 commented on apps/docs/app/docs/components/pagination/page.md
> +## showSizeChanger
Write it in capitalized casing

2023-12-08 08:06 UTC, LuckySharma014 commented on apps/docs/app/docs/components/pagination/page.md
> +| showTotal        | Callback function to display total and range info.               | `(total:number,range:string) => ReactNode or string` |            |
Pass dash ( - ) in default column if there is no default

2023-12-08 08:06 UTC, LuckySharma014 commented on apps/docs/lib/navigation.ts
> +      },
Position this before password field

2023-12-09 04:39 UTC, LuckySharma014 commented on libs/ui/src/pagination/pagination.tsx
You need to change the file casing via github.com

2023-12-09 04:42 UTC, LuckySharma014 commented on libs/ui/src/pagination/pagination.tsx
> +    const onPageChange = (value: number) => onChangeHandle(value, page);
Still variable names are very confusing

2023-12-09 04:46 UTC, LuckySharma014 commented on libs/ui/src/pagination/PaginationButtons.tsx
> +          )}
You have made class variable as internal variable which is not the convention we use

2023-12-13 05:27 UTC, MathurAditya724 approved these changes

2023-12-13 05:30 UTC, LuckySharma014 approved these changes

2023-12-13 05:42 UTC, merged